channels:
- conda-forge
- pytorch
- anaconda
dependencies:
- python=3.7.9
- pip:
  - adal==1.2.7
  - applicationinsights==0.11.10
  - argcomplete==2.0.0
  - attrs==22.1.0
  - azure-common==1.1.28
  - azure-core==1.26.1
  - azure-graphrbac==0.61.1
  - azure-identity==1.12.0
  - azure-mgmt-authorization==3.0.0
  - azure-mgmt-containerregistry==10.0.0
  - azure-mgmt-core==1.3.2
  - azure-mgmt-keyvault==10.1.0
  - azure-mgmt-resource==21.2.1
  - azure-mgmt-storage==20.1.0
  - azure-storage-blob==12.13.0
  - azure-storage-queue==12.5.0
  - azureml-automl-core==1.48.0
  - azureml-automl-runtime==1.48.0.post1
  - azureml-core==1.48.0
  - azureml-dataprep==4.8.3
  - azureml-dataprep-native==38.0.0
  - azureml-dataprep-rslex==2.15.1
  - azureml-dataset-runtime==1.48.0
  - azureml-defaults==1.48.0
  - azureml-inference-server-http==0.7.7
  - azureml-interpret==1.48.0
  - azureml-mlflow==1.48.0
  - azureml-pipeline-core==1.48.0
  - azureml-responsibleai==1.48.0
  - azureml-telemetry==1.48.0
  - azureml-train-automl-client==1.48.0
  - azureml-train-automl-runtime==1.48.0
  - azureml-train-core==1.48.0
  - azureml-train-restclients-hyperdrive==1.48.0
  - azureml-training-tabular==1.48.0
  - backcall==0.2.0
  - backports-tempfile==1.0
  - backports-weakref==1.0.post1
  - bcrypt==4.0.1
  - bokeh==2.4.3
  - boto==2.49.0
  - cachetools==5.2.0
  - charset-normalizer==2.1.1
  - contextlib2==21.6.0
  - cython==0.29.17
  - dask==2021.6.0
  - databricks-cli==0.17.4
  - dataclasses==0.6
  - debugpy==1.6.4
  - decorator==5.1.1
  - dice-ml==0.9
  - dill==0.3.6
  - distributed==2021.6.0
  - distro==1.8.0
  - docker==6.0.1
  - dotnetcore2==3.1.23
  - econml==0.14.0
  - entrypoints==0.4
  - erroranalysis==0.3.13
  - fairlearn==0.7.0
  - fire==0.5.0
  - flask==2.2.2
  - flask-cors==3.0.10
  - flatbuffers==22.12.6
  - fsspec==2022.11.0
  - gensim==3.8.3
  - gitdb==4.0.10
  - gitpython==3.1.29
  - google-api-core==2.11.0
  - google-auth==2.15.0
  - googleapis-common-protos==1.57.0
  - gunicorn==20.1.0
  - h5py==3.7.0
  - heapdict==1.0.1
  - humanfriendly==10.0
  - importlib-resources==5.10.1
  - inference-schema==1.5
  - interpret-community==0.27.0
  - interpret-core==0.2.7
  - ipykernel==6.6.0
  - ipython==7.34.0
  - isodate==0.6.1
  - itsdangerous==2.1.2
  - jedi==0.18.2
  - jeepney==0.8.0
  - jinja2==3.1.2
  - jsonpickle==2.2.0
  - jsonschema==4.17.3
  - jupyter-client==7.4.8
  - jupyter-core==4.12.0
  - keras2onnx==1.6.0
  - knack==0.10.1
  - lightgbm==3.2.1
  - locket==1.0.0
  - markupsafe==2.0.1
  - matplotlib-inline==0.1.6
  - ml-wrappers==0.2.2
  - mlflow-skinny==1.30.0
  - msal==1.20.0
  - msal-extensions==1.0.0
  - msgpack==1.0.4
  - msrest==0.7.1
  - msrestazure==0.6.4
  - ndg-httpsclient==0.5.1
  - nest-asyncio==1.5.6
  - networkx==2.5
  - nimbusml==1.8.0
  - numba==0.55.2
  - oauthlib==3.2.2
  - onnx==1.12.0
  - onnxconverter-common==1.6.0
  - onnxmltools==1.4.1
  - onnxruntime==1.11.1
  - opencensus==0.11.0
  - opencensus-context==0.1.3
  - opencensus-ext-azure==1.1.7
  - packaging==21.3
  - paramiko==2.12.0
  - parso==0.8.3
  - partd==1.3.0
  - pathspec==0.10.3
  - patsy==0.5.3
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - pkginfo==1.9.2
  - pkgutil-resolve-name==1.3.10
  - pmdarima==1.7.1
  - portalocker==2.6.0
  - prompt-toolkit==3.0.36
  - protobuf==3.20.1
  - ptyprocess==0.7.0
  - pyarrow==9.0.0
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pygments==2.13.0
  - pyjwt==2.6.0
  - pynacl==1.5.0
  - pyrsistent==0.19.2
  - pyyaml==6.0
  - pyzmq==24.0.1
  - raiutils==0.2.0
  - requests==2.28.1
  - requests-oauthlib==1.3.1
  - responsibleai==0.23.0
  - rsa==4.9
  - scipy==1.5.3
  - secretstorage==3.3.3
  - semver==2.13.0
  - skl2onnx==1.4.9
  - sklearn-pandas==1.7.0
  - slicer==0.0.7
  - smart-open==1.9.0
  - smmap==5.0.0
  - sortedcontainers==2.4.0
  - sparse==0.13.0
  - sqlparse==0.4.3
  - statsmodels==0.11.1
  - tabulate==0.9.0
  - tblib==1.7.0
  - termcolor==2.1.1
  - toolz==0.12.0
  - tornado==6.2
  - traitlets==5.7.1
  - wcwidth==0.2.5
  - websocket-client==1.4.2
  - werkzeug==2.2.2
  - wrapt==1.12.1
  - zict==2.2.0
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- _py-xgboost-mutex=2.0
- arviz=0.13.0
- binutils_impl_linux-64=2.36.1
- binutils_linux-64=2.36
- boto3=1.15.18
- botocore=1.18.18
- brotli=1.0.9
- brotli-bin=1.0.9
- brotlipy=0.7.0
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2022.12.7
- certifi=2022.12.7
- cffi=1.14.6
- cftime=1.6.2
- cloudpickle=1.6.0
- colorama=0.4.6
- convertdate=2.4.0
- cryptography=38.0.2
- curl=7.86.0
- cycler=0.11.0
- ephem=4.1.3
- fbprophet=0.7.1
- fonttools=4.38.0
- freetype=2.12.1
- gcc_impl_linux-64=7.5.0
- gcc_linux-64=7.5.0
- gxx_impl_linux-64=7.5.0
- gxx_linux-64=7.5.0
- hdf4=4.2.15
- hdf5=1.12.2
- holidays=0.10.3
- icu=70.1
- idna=3.4
- importlib-metadata=4.11.4
- importlib_metadata=4.11.4
- jmespath=0.10.0
- joblib=0.14.1
- jpeg=9e
- kernel-headers_linux-64=2.6.32
- keyutils=1.6.1
- kiwisolver=1.4.4
- korean_lunar_calendar=0.3.1
- krb5=1.19.3
- lcms2=2.14
- ld_impl_linux-64=2.36.1
- lerc=4.0.0
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcblas=3.9.0
- libcurl=7.86.0
- libdeflate=1.14
- libedit=3.1.20191231
- libev=4.33
- libffi=3.3
- libgcc-ng=12.2.0
- libgfortran-ng=12.2.0
- libgfortran5=12.2.0
- libgomp=12.2.0
- libiconv=1.17
- liblapack=3.9.0
- libnetcdf=4.8.1
- libnghttp2=1.47.0
- libopenblas=0.3.21
- libpng=1.6.39
- libsqlite=3.40.0
- libssh2=1.10.0
- libstdcxx-ng=12.2.0
- libtiff=4.4.0
- libwebp-base=1.2.4
- libxcb=1.13
- libxgboost=1.3.3
- libxml2=2.10.3
- libzip=1.9.2
- libzlib=1.2.13
- llvmlite=0.38.1
- lunarcalendar=0.0.9
- matplotlib-base=3.5.3
- munkres=1.1.4
- ncurses=6.3
- netcdf4=1.6.1
- numpy=1.21.6
- openjpeg=2.5.0
- openssl=1.1.1s
- pandas=1.1.5
- pillow=9.2.0
- pip=20.2.4
- psutil=5.9.3
- pthread-stubs=0.4
- py-cpuinfo=5.0.0
- py-xgboost=1.3.3
- pycparser=2.21
- pymeeus=0.5.12
- pyopenssl=22.1.0
- pyparsing=3.0.9
- pysocks=1.7.1
- pystan=2.19.1.1
- python-dateutil=2.8.2
- python_abi=3.7
- pytz=2022.6
- readline=8.1.2
- s3transfer=0.3.7
- scikit-learn=0.22.1
- setuptools=59.8.0
- setuptools-git=1.2
- shap=0.39.0
- six=1.16.0
- sqlite=3.40.0
- sysroot_linux-64=2.12
- tk=8.6.12
- tqdm=4.64.1
- typing-extensions=4.4.0
- typing_extensions=4.4.0
- unicodedata2=14.0.0
- urllib3=1.25.11
- wheel=0.38.4
- xarray=0.20.2
- xarray-einstats=0.2.2
- xorg-libxau=1.0.9
- xorg-libxdmcp=1.1.3
- xz=5.2.6
- zipp=3.11.0
- zlib=1.2.13
- zstd=1.5.2
name: project_environment
